[project]
name = "enterprise_api_ingestion_platform"
version = "0.0.18"
authors = [{ name = "karan_vsk@hotmail.com" }]
requires-python = ">=3.10,<3.13"

dependencies = [
    "requests>=2.32.0",
    "azure-identity>=1.17.1",
    "azure-storage-file-datalake>=12.18.1",
]

[dependency-groups]
dev = [
    "pytest",
    "ruff",
    "databricks-dlt",
    "databricks-connect>=15.4,<15.5",
    "ipykernel",
]

[project.scripts]
main = "enterprise_api_ingestion_platform.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 120

[tool.hatch.build.targets.wheel]
packages = ["src/enterprise_api_ingestion_platform"]

[tool.ruff.lint.per-file-ignores]
"src/enterprise_api_ingestion_platform/bronze_pipeline/*.py" = ["F821"]
"src/enterprise_api_ingestion_platform/silver/*.py" = ["F821"]
